// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFMg9IvoaeyQxNVBfAcLkWNFIzTMLDRdk',
    appId: '1:996894456303:web:0bbb715259857354665e1a',
    messagingSenderId: '996894456303',
    projectId: 'around-you-5942e',
    authDomain: 'around-you-5942e.firebaseapp.com',
    storageBucket: 'around-you-5942e.firebasestorage.app',
    measurementId: 'G-LWNZ8SCCKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyh02HCS3jpVLNCixeNelsp43mUSssUS4',
    appId: '1:996894456303:android:93fa6e956243b7d7665e1a',
    messagingSenderId: '996894456303',
    projectId: 'around-you-5942e',
    storageBucket: 'around-you-5942e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt180nJIXw7Zh-OQ01STsBG7MDcip-yL4',
    appId: '1:996894456303:ios:60a707baf741638e665e1a',
    messagingSenderId: '996894456303',
    projectId: 'around-you-5942e',
    storageBucket: 'around-you-5942e.firebasestorage.app',
    iosBundleId: 'com.example.aroundYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt180nJIXw7Zh-OQ01STsBG7MDcip-yL4',
    appId: '1:996894456303:ios:60a707baf741638e665e1a',
    messagingSenderId: '996894456303',
    projectId: 'around-you-5942e',
    storageBucket: 'around-you-5942e.firebasestorage.app',
    iosBundleId: 'com.example.aroundYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFMg9IvoaeyQxNVBfAcLkWNFIzTMLDRdk',
    appId: '1:996894456303:web:18883642b1eb721b665e1a',
    messagingSenderId: '996894456303',
    projectId: 'around-you-5942e',
    authDomain: 'around-you-5942e.firebaseapp.com',
    storageBucket: 'around-you-5942e.firebasestorage.app',
    measurementId: 'G-16244GMMYH',
  );
}
